# Generated by Django 6.0.1 on 2026-02-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='county',
            new_name='country',
        ),
    ]
